"""Module containing utils"""
import numpy as np
import pandas as pd
import scipy.linalg as la
from numpy.polynomial.legendre import Legendre


def _compute_tsnr_from_2d(data: np.ndarray, confounds: pd.DataFrame) -> np.ndarray:
    """Compute tSNR from 2D data array (n_timepoints, n_features).

    This is the shared implementation used by both volume and surface tSNR
    computation.
    """
    data_mean = data.mean(axis=0)
    data_clean = clean_data(data, confounds)
    std = data_clean.std(axis=0)
    std[std < 1e-8] = 1
    return data_mean / std


def compute_tsnr(data: np.ndarray, confounds: pd.DataFrame) -> np.ndarray:
    """Compute tSNR on data by first regressing out the following nuisance
    regressors:

    - six motion parameters and their derivatives
    - global signal
    - framewise displacement
    - six aCompCor components
    - polynomial regressors up to second order

    Parameters
    ----------
    data : array of shape (dim1, dim2, dim3, n_volumes)
        EPI data
    confounds : pandas Dataframe
        dataframe containing confounds generated by fmriprep

    Returns
    ------
    tsnr : array of shape (dim1, dim2, dim3)
        temporal SNR array
    """
    data = data.T
    orig_shape = data.shape
    data_2d = data.reshape(orig_shape[0], -1)
    tsnr = _compute_tsnr_from_2d(data_2d, confounds)
    return tsnr.reshape(orig_shape[1:]).T


def compute_tsnr_surface(data: np.ndarray, confounds: pd.DataFrame) -> np.ndarray:
    """Compute tSNR for surface data.

    Applies the same confound regression as compute_tsnr() but for 2D surface
    time series data (e.g., from fsaverage6 GIFTI files).

    Parameters
    ----------
    data : array of shape (n_timepoints, n_vertices)
        Surface time series data from GIFTI
    confounds : pandas DataFrame
        Confounds DataFrame from fMRIprep

    Returns
    -------
    tsnr : array of shape (n_vertices,)
        tSNR per vertex
    """
    return _compute_tsnr_from_2d(data, confounds)


def make_poly_regressors(n_samples: int, order: int = 2) -> np.ndarray:
    """Create polynomial regressors using Legendre basis."""
    x = np.linspace(-1, 1, n_samples)
    columns = [np.ones(n_samples)]
    columns.extend(Legendre.basis(d + 1)(x) for d in range(order))
    return np.column_stack(columns)


def clean_data(data: np.ndarray, confounds: pd.DataFrame) -> np.ndarray:
    """Clean data by regressing out the following nuisance regressors:

    - six motion parameters and their derivatives
    - global signal
    - framewise displacement
    - six aCompCor components
    - polynomial regressors up to second order

    Parameters
    ----------
    data : array of shape (n_volumes, n_features)
        flattened EPI data
    confounds : pandas Dataframe
        dataframe containing confounds generated by fmriprep

    Returns
    -------
    data_clean : array of shape (n_volumes, n_features)
        denoised data
    """
    confound_columns = [
        'global_signal',
        'framewise_displacement',
        'trans_x', 'trans_x_derivative1',
        'trans_y', 'trans_y_derivative1',
        'trans_z', 'trans_z_derivative1',
        'rot_x', 'rot_x_derivative1',
        'rot_y', 'rot_y_derivative1',
        'rot_z', 'rot_z_derivative1',
    ]
    confound_columns += [f"a_comp_cor_{c:02d}" for c in range(6)]

    X = confounds[confound_columns].values.copy()
    X[np.isnan(X)] = 0.0
    X = np.hstack((X, make_poly_regressors(X.shape[0])))

    data_mean = data.mean(0)
    data_centered = data - data_mean
    coef = la.lstsq(X, data_centered)[0]
    return data_centered - X @ coef + data_mean
